### PR TITLE
wip | max sub span fix #109

### LINKED ISSUE #109: Is there a maximum of sub-spans?
Is there a (intended) maximum of sub-spans? I'm creating a larger trace of a request with several SQL statements (a span for each). It works up to a total of 59 spans (depth 4), where one span has 50 sub-spans (children). If I add more than 50 sub-spans, the trace is not found in Jaeger UI and the log of `jaegertracing/all-in-one:1.26` shows two errors

```json
{
  "level": "error",
  "ts": 1632257043.8104687,
  "caller": "processors/thrift_processor.go:123",
  "msg": "Processor failed",
  "error": "*jaeger.Batch error reading struct: *jaeger.Span error reading struct: *jaeger.Tag error reading struct: *jaeger.Tag field 0 read error: EOF",
  "stacktrace": "github.com/jaegertracing/jaeger/cmd/agent/app/processors.(*ThriftProcessor).processBuffer\n\tgithub.com/jaegertracing/jaeger/cmd/agent/app/processors/thrift_processor.go:123\ngithub.com/jaegertracing/jaeger/cmd/agent/app/processors.NewThriftProcessor.func2\n\tgithub.com/jaegertracing/jaeger/cmd/agent/app/processors/thrift_processor.go:87"
}
```

```json
{
  "level": "error",
  "ts": 1632257043.824714,
  "caller": "processors/thrift_processor.go:123",
  "msg": "Processor failed",
  "error": "EOF",
  "stacktrace": "github.com/jaegertracing/jaeger/cmd/agent/app/processors.(*ThriftProcessor).processBuffer\n\tgithub.com/jaegertracing/jaeger/cmd/agent/app/processors/thrift_processor.go:123\ngithub.com/jaegertracing/jaeger/cmd/agent/app/processors.NewThriftProcessor.func2\n\tgithub.com/jaegertracing/jaeger/cmd/agent/app/processors/thrift_processor.go:87"
}
```

---

`jonahgeorge/jaeger-client-php` version `1.2.4`. My configuration:

```php
$config = new \Jaeger\Config(
  [
    'sampler' => [
      'type' => \Jaeger\SAMPLER_TYPE_CONST,
      'param' => true,
    ],
    'logging' => true,
    "tags" => [
      "foo" => "bar",
    ],
    "local_agent" => [
      "reporting_host" => "jaeger",
    ],
    'dispatch_mode' => \Jaeger\Config::JAEGER_OVER_BINARY_UDP,
  ],
  'my-app',
);
```

### PR DESCRIPTION
**Pull request by pekhota**
#109 fix

### CODE REVIEW

File: src/Jaeger/Sender/JaegerSender.php [hunk 1]
```diff
@@ -52,10 +66,12 @@ class JaegerSender implements SenderInterface
      */
     public function __construct(
         AgentIf $agentClient,
+        int $maxBufferLength,
         LoggerInterface $logger = null,
         SpanToJaegerMapper $mapper = null
     ) {
         $this->agentClient = $agentClient;
+        $this->maxBufferLength = $maxBufferLength;
```
Comment (sergeyklay) [inline src/Jaeger/Sender/JaegerSender.php:74]: I propose to not break backward compatibility. 
```diff
 public function __construct(
     AgentIf $agentClient,
     LoggerInterface $logger = null,
     SpanToJaegerMapper $mapper = null
 ) {
    $this->agentClient = $agentClient;
+    $this->maxBufferLength = USE_SOME_DEFAULT_CONSTANT_HERE;
     $this->logger = $logger ?? new NullLogger();
     $this->mapper = $mapper ?? new SpanToJaegerMapper();
 }
```

Then, add for this class something like:

```php
public function setMaxBufferLength($maxBufferLength)
{
    $this->maxBufferLength = $maxBufferLength;
}
```

This will allow use sender as follows:
```php
$sender = new JaegerSender($client, $this->config->getLogger());
$sender->setMaxBufferLength( $this->config->getMaxBufferLength());
```

File: src/Jaeger/Sender/JaegerSender.php [hunk 2]
```diff
@@ -110,6 +126,50 @@ private function send(array $spans)
...
+        foreach ($chunks as $chunk) {
+            /** @var JaegerThriftSpan[] $chunk */
+            $this->emitJaegerBatch($chunk);
+        }
+    }
+
+    /**
+     * @param JaegerThriftSpan $span
+     */
+    private function getBufferLength($span) {
```
Comment (sergeyklay) [inline src/Jaeger/Sender/JaegerSender.php:139]:
```suggestion
    private function getBufferLength($span)
    {
```

File: src/Jaeger/Sender/JaegerSender.php [hunk 3]
```diff
@@ -110,6 +126,50 @@ private function send(array $spans)
...
+        $memoryBuffer = new TMemoryBuffer();
+        $span->write(new TBinaryProtocol($memoryBuffer));
+        return $memoryBuffer->available();
+    }
+
+    private function chunkSplit(array $spans): array {
```
Comment (sergeyklay) [inline src/Jaeger/Sender/JaegerSender.php:145]:
```suggestion
    private function chunkSplit(array $spans): array
    {
```

File: src/Jaeger/Sender/JaegerSender.php [hunk 4]
```diff
@@ -110,6 +126,50 @@ private function send(array $spans)
...
+            }
+
+            $chunks[$chunkId][] = $span;
+            $actualBufferSize += $spanBufferLength;
+        }
+
+        return $chunks;
+    }
+
+    private function emitJaegerBatch(array $spans) {
```
Comment (sergeyklay) [inline src/Jaeger/Sender/JaegerSender.php:172]:
```suggestion
    private function emitJaegerBatch(array $spans)
    {
```

File: tests/Jaeger/Sender/JaegerThriftSenderTest.php [hunk 5]
```diff
@@ -40,7 +40,7 @@ public function testFlush(): void
         $span->method('getContext')->willReturn($this->context);
 
         $client = $this->createMock(AgentClient::class);
-        $sender = new JaegerSender($client);
+        $sender = new JaegerSender($client, 64000);
```
Comment (sergeyklay) [inline tests/Jaeger/Sender/JaegerThriftSenderTest.php:43]: See my comment above

**Review by sergeyklay — CHANGES_REQUESTED** [review]

**Comment by pekhota** [comment]
All comments have been fixed.

**Review by sergeyklay — APPROVED** [review]

**Comment by sergeyklay** [comment]
Thank you
